databases:
  - name: remoreks
    databaseName: remoreks
    user: postgres

services:
  - type: web
    name: remorex
    env:  python
    buildCommand: "./build.sh"
    startCommand: "gunicorn remorex.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: remoreks
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4



