# Generated by Django 4.1.3 on 2022-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.CharField(default="BMW", max_length=500),
            preserve_default=False,
        ),
    ]
