# Generated by Django 4.1.3 on 2022-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yard", "0002_car_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                ("cars", models.ManyToManyField(to="yard.car")),
            ],
        ),
    ]
