# Generated by Django 4.1.3 on 2022-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yard", "0003_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
